# Generated by Django 4.2.3 on 2023-07-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_todo_slug_alter_todo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
