# Generated by Django 4.2.3 on 2023-07-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_todo_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
